/**
 * Unit tests for the Cargo security manifest plugin.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { parseCargoManifest } from './cargo';

describe('parseCargoManifest', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kirograph-cargo-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  function writeCargoToml(content: string, dir?: string): string {
    const targetDir = dir ?? tmpDir;
    fs.mkdirSync(targetDir, { recursive: true });
    const filePath = path.join(targetDir, 'Cargo.toml');
    fs.writeFileSync(filePath, content);
    return filePath;
  }

  it('extracts simple string dependencies with production scope', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = "1.35"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    const serde = deps.find(d => d.name === 'serde');
    expect(serde).toBeDefined();
    expect(serde!.declaredConstraint).toBe('1.0');
    expect(serde!.scope).toBe('production');
    expect(serde!.ecosystem).toBe('cargo');

    const tokio = deps.find(d => d.name === 'tokio');
    expect(tokio).toBeDefined();
    expect(tokio!.declaredConstraint).toBe('1.35');
    expect(tokio!.scope).toBe('production');
  });

  it('extracts table format dependencies with version field', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.find(d => d.name === 'serde')!.declaredConstraint).toBe('1.0');
    expect(deps.find(d => d.name === 'tokio')!.declaredConstraint).toBe('1.35');
  });

  it('extracts dev-dependencies with development scope', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.every(d => d.scope === 'development')).toBe(true);
  });

  it('extracts build-dependencies with development scope', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.every(d => d.scope === 'development')).toBe(true);
    expect(deps.find(d => d.name === 'cc')!.declaredConstraint).toBe('1.0');
  });

  it('handles all dependency sections together', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = "1.0"

[dev-dependencies]
criterion = "0.5"

[build-dependencies]
cc = "1.0"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(3);
    expect(deps.find(d => d.name === 'serde')!.scope).toBe('production');
    expect(deps.find(d => d.name === 'criterion')!.scope).toBe('development');
    expect(deps.find(d => d.name === 'cc')!.scope).toBe('development');
  });

  it('resolves versions from Cargo.lock', async () => {
    writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = "1"
`);

    const lockContent = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;
    fs.writeFileSync(path.join(tmpDir, 'Cargo.lock'), lockContent);

    const manifestPath = path.join(tmpDir, 'Cargo.toml');
    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.find(d => d.name === 'serde')!.resolvedVersion).toBe('1.0.193');
    expect(deps.find(d => d.name === 'tokio')!.resolvedVersion).toBe('1.35.1');
  });

  it('leaves resolvedVersion undefined when no Cargo.lock exists', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = "1.0"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(1);
    expect(deps[0].resolvedVersion).toBeUndefined();
  });

  it('handles path dependencies with no version (uses * constraint)', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
my-lib = { path = "../my-lib" }
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(1);
    expect(deps[0].name).toBe('my-lib');
    expect(deps[0].declaredConstraint).toBe('*');
  });

  it('handles git dependencies with no version (uses * constraint)', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
my-crate = { git = "https://github.com/user/repo" }
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(1);
    expect(deps[0].name).toBe('my-crate');
    expect(deps[0].declaredConstraint).toBe('*');
  });

  it('handles table-style individual dependency sections', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.35"
features = ["full"]
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.find(d => d.name === 'serde')!.declaredConstraint).toBe('1.0');
    expect(deps.find(d => d.name === 'tokio')!.declaredConstraint).toBe('1.35');
    expect(deps.every(d => d.scope === 'production')).toBe(true);
  });

  it('returns empty array for unreadable file', async () => {
    const fakePath = path.join(tmpDir, 'nonexistent', 'Cargo.toml');
    const deps = await parseCargoManifest(fakePath, tmpDir);
    expect(deps).toEqual([]);
  });

  it('returns empty array for Cargo.toml with no dependency sections', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"
edition = "2021"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);
    expect(deps).toEqual([]);
  });

  it('skips comment lines in dependency sections', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
# This is a comment
serde = "1.0"
# Another comment
tokio = "1.35"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(2);
    expect(deps.find(d => d.name === 'serde')).toBeDefined();
    expect(deps.find(d => d.name === 'tokio')).toBeDefined();
  });

  it('sets sourceManifest as relative path', async () => {
    const subDir = path.join(tmpDir, 'crates', 'sub');
    const manifestPath = writeCargoToml(`
[package]
name = "sub-crate"
version = "0.1.0"

[dependencies]
serde = "1.0"
`, subDir);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(1);
    expect(deps[0].sourceManifest).toBe('crates/sub/Cargo.toml');
  });

  it('handles mixed simple and table format in same section', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(3);
    expect(deps.find(d => d.name === 'log')!.declaredConstraint).toBe('0.4');
    expect(deps.find(d => d.name === 'serde')!.declaredConstraint).toBe('1.0');
    expect(deps.find(d => d.name === 'rand')!.declaredConstraint).toBe('0.8');
  });

  it('handles version constraints with operators', async () => {
    const manifestPath = writeCargoToml(`
[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = ">=1.0, <2.0"
tokio = "~1.35"
rand = "^0.8"
`);

    const deps = await parseCargoManifest(manifestPath, tmpDir);

    expect(deps).toHaveLength(3);
    expect(deps.find(d => d.name === 'serde')!.declaredConstraint).toBe('>=1.0, <2.0');
    expect(deps.find(d => d.name === 'tokio')!.declaredConstraint).toBe('~1.35');
    expect(deps.find(d => d.name === 'rand')!.declaredConstraint).toBe('^0.8');
  });
});
